image:
  file: .gitpod.Dockerfile

# tasks:
#   - init: /usr/bin/start-vnc-session.sh
#   - command: zsh
#   - command: mkdir -p ~/.config/Google && ln -s `pwd`/AndroidStudio4.2-config ~/.config/Google/AndroidStudio4.2 && mkdir -p ~/.local/share/Google && ln -s `pwd`/AndroidStudio4.2-local ~/.local/share/Google/AndroidStudio4.2 && cd /usr/local/android-studio/bin/ && ./studio.sh
  
ports:
  - port: 5900
    onOpen: ignore
  - port: 6080
    onOpen: open-preview
  - port: 6942
    onOpen: ignore
